# Prometheus configuration for BioNewsBot Notification Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bionewsbot-monitor'

scrape_configs:
  # Notification Service metrics
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notifications:8001']
    metrics_path: '/webhooks/metrics'
    scrape_interval: 10s

  # Redis exporter (if using)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
