blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@bionewsbot.com
    about: Please report security vulnerabilities via email
  - name: Community Support
    url: https://github.com/romwil/bionewsbot/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/romwil/bionewsbot/wiki
    about: Check our documentation for common questions
