global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bionewsbot-monitor'

scrape_configs:
  # Backend API metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scheduler metrics
  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification service metrics
  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
